// @ts-check
// Sidebar config for Showcase Operations Master
// Auto-generates sidebar from /docs folder structure

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  projectsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Projects',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'projects'}],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'templates'}],
    },
  ],
};

export default sidebars;
